# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "1 1 1 * *"}]
  # Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
#   push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: gautam-404
          template: classic
          base: header, metadata
          config_timezone: Asia/Kolkata
          
          
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: half-year
          
#           plugin_languages: yes
#           plugin_languages_sections: most-used
          

          config_order: base.header

#           plugin_wakatime: yes
#           plugin_wakatime_sections: time, languages-graphs, projects-graphs, os-graphs
#           plugin_wakatime_languages_other: yes
#           plugin_wakatime_days: 7
#           plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
